language: python
python:
  - "3.2"
  - "3.4"
  - "3.6"
  - "3.8"
  - "3.10"
  - "3.11"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: make test
