name: Python Colorspace Testing

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.9", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Required Packages
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-mpl
          pip install pytest-cov
          pip install coverage
          pip install matplotlib
          pip install numpy
          pip install -e .
      - name: Coverage
        run: |
          pytest -s

