name: Python Colorspace Testing

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
          #python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-mpl
          pip install pytest-cov
          pip install matplotlib
          pip install numpy
          python setup.py install

      - name: Test with pytest
        run: |
          pytest --cov=src/colorspace --cov-report=xml --cov-report=html
        continue-on-error: true
          #pytest -s src/colorspace/tests --junitxml=test-results.xml --cov=com --cov-report=term-missing:skip-covered --cov-report=html | tee pytest.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

      - name: Get Cover 
        uses: orgoro/coverage@v3.1
        with:
            coverageFile: coverage.xml
            token: ${{ secrets.GITHUB_TOKEN }}





