name: Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Change to your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_devel.txt
        python setup.py install

    #- name: Execute preparation script
    #  run: |
    #    python make_docs/main.py  # Generates qmd files

    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.37/quarto-1.5.37-linux-amd64.deb -O quarto.deb # pre-release version!
        sudo dpkg -i quarto.deb

    - name: Render Quarto documents
      run: |
        pyp2qmd examples --package colorspace
        cd _examples && for file in *.qmd; do quarto render $$file; done


