name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Change to your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_devel.txt
        python setup.py install

    #- name: Install Quarto
    #  run: |
    #    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.37/quarto-1.5.37-linux-amd64.deb -O quarto.deb # pre-release version!
    #    sudo dpkg -i quarto.deb
    - name: Installing quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Manipulate quarto yaml file
      run: |
        P_VERSION=`python --version | awk '{print $2}'`
        Q_VERSION=`quarto --version`
        sed -i 's/{{QUARTO_VERSION}}/'${Q_VERSION}'/g' _quarto/_quarto.yml
        sed -i 's/{{PYTHON_VERSION}}/'${P_VERSION}'/g' _quarto/_quarto.yml

    - name: Render quarto documents
      run: |
        quarto render _quarto

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_quarto/_site  # Change to the output directory of your quarto render

