name: Sphinx build

on:
  push:
    branches:
      - main

jobs:
  sphinx_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - name: Git checkout
        uses: actions/checkout
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7    # Python version to build the html sphinx documentation
          environment-file: devtools/conda-envs/docs_env.yaml    # Path to the documentation conda environment
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Installing the library
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt
          python setup.py install
      - name: Running the Sphinx to gh-pages Action
        uses: retostauffer/python-colorspace@main
        with:
          branch: main
          dir_docs: source
          sphinxapiopts: '--separate -o . ../'
          sphinxopts: ''
