name: Sphinx build

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Setting up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Upgrading pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          printf " =================== "
          pwd
          ls -l
          python3 -m pip install -r ./requirements.txt

      - name: Call make html
        shell: bash
        run: make html
